language: node_js

node_js:
- "8"

branches:
  only:
  - master
  - /^greenkeeper/.*$/

before_script:
- yarn global add typescript
- tsc -v
- yarn install
- yarn run build

script:
- yarn run test:coveralls