language: node_js

node_js:
- "8"

branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
  - yarn global add typescript
  - yarn install

script:
  - yarn run lint
  - yarn run build
  - yarn run test:coveralls