defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:8.0

whitelist: &whitelist
  paths:
  - .npmignore
  - coverage/*
  - dist/*
  - node_modules/*
  - src/*
  - package.json
  - README.md
  - tsconfig.json
  - tslint.json
version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run:
        name: Install Dependencies
        command: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - persist_to_workspace:
        root: ~/repo
        <<: *whitelist

  lint:
    <<: *defaults

    steps:
    - attach_workspace:
        at: ~/repo

    - run:
        name: Lint TypeScript code
        command: yarn lint

  test:
    <<: *defaults

    steps:
    - attach_workspace:
        at: ~/repo

    - run:
        name: Test TypeScript code
        command: yarn test:coveralls

    - persist_to_workspace:
        root: ~/repo
        <<: *whitelist

  coveralls:
    <<: *defaults

    steps:
    - attach_workspace:
        at: ~/repo

    - run:
        name: Submit coverage report to Coveralls.io
        command: yarn coveralls

  build:
    <<: *defaults

    steps:
    - attach_workspace:
        at: ~/repo

    - run:
        name: Build TypeScript code
        command: yarn build

    - persist_to_workspace:
        root: ~/repo
        <<: *whitelist

workflows:
  version: 2

  build:
    jobs:
    - checkout
    - test:
        requires:
        - checkout
    - lint:
        requires:
        - checkout
    - coveralls:
        requires:
        - test
    - build:
        requires:
        - test
        - lint